<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2022-09-22T23:36:17" hostname="RASHID" time="0.011">
  <properties/>
  <testcase name="givenAValidUser_whenCallsUpdateUserWithInvalidName_thenShouldReturnsDomainException()" classname="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" time="0.003"/>
  <testcase name="givenAValidCommand_whenCallsUpdateUser_thenShouldReturnUserId()" classname="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" time="0.003"/>
  <testcase name="givenAValidDowntime_whenCallsUpdateDowntimeWithRandomGatewayError_thenShouldReturnsGatewayError()" classname="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" time="0.002"/>
  <testcase name="givenAValidUser_whenCallsUpdateUserWithNullName_thenShouldReturnsDomainException()" classname="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" time="0.001"/>
  <testcase name="givenAnInvalidId_whenCallsUpdateDowntime_thenShouldReturnsNotFoundException()" classname="io.sanctuary.bs.api.application.user.update.UpdateUserUseCaseTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
